excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://dataviz-blog.github.io
title: Interactive data visualisation in your blog
email: errolkjlloyd@gmail.com
author: Errol Lloyd
description: Course material for short course Interactive data visualisation in your blog.
paginate: 8
google_analytics: 
